// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210814063534_AddedSomeTables")]
    partial class AddedSomeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.BalanceEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BalanceEquipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a50bf529-1712-44a8-b12d-d86e336fcf0c"),
                            Code = "01BAL",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Balance",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Moisture.MoistureContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateChecked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTested")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaterialDryMass")
                        .HasColumnType("float");

                    b.Property<Guid?>("PreparationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SelectDryingTemperature")
                        .HasColumnType("bit");

                    b.Property<bool>("SelectInsufficientSampleMass")
                        .HasColumnType("bit");

                    b.Property<bool>("SelectMaterialExcluded")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TareAndMaterialDryMass")
                        .HasColumnType("float");

                    b.Property<double>("TareAndMaterialWetMass")
                        .HasColumnType("float");

                    b.Property<string>("TareId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TareMass")
                        .HasColumnType("float");

                    b.Property<string>("TesterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("WaterContentPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MoistureContents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d865d8d-d05a-43b1-a739-0cec7a3a1fc1"),
                            CheckerName = "Andrew Phan",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTested = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialDryMass = 2225.6999999999998,
                            PreparationId = new Guid("2b1e6481-0c73-434e-8756-061e20e16d70"),
                            ProjectId = new Guid("8606b885-bde6-4572-8c75-9e714858cf67"),
                            SampleId = new Guid("45d8f01c-5bca-4267-8d68-5f8f983fedc6"),
                            SelectDryingTemperature = false,
                            SelectInsufficientSampleMass = false,
                            SelectMaterialExcluded = false,
                            SourceMaterialId = new Guid("29d35a08-3e09-4108-bef4-419b007dcb38"),
                            SpecificationId = new Guid("03e9993b-b782-4e84-81a9-f9489cb4a689"),
                            TareAndMaterialDryMass = 2525.6999999999998,
                            TareAndMaterialWetMass = 2859.5999999999999,
                            TareId = "MT001",
                            TareMass = 300.0,
                            TesterName = "Andrew Phan",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaterContentPercentage = 15.0
                        });
                });

            modelBuilder.Entity("Domain.Moisture.SourceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialDesciption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SourceMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29d35a08-3e09-4108-bef4-419b007dcb38"),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialDesciption = "Soil and Rock",
                            SourceName = "Source01",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Moisture.Specification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03e9993b-b782-4e84-81a9-f9489cb4a689"),
                            Code = "01Spec",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Specification01",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.OvenEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OvenEquipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("226b5d9f-3e75-4b6a-9d46-62725d947f90"),
                            Code = "01Ove",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oven",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Preparation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BalanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("DryingTemperature")
                        .HasColumnType("float");

                    b.Property<string>("MaterialExcluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("VisualNomialPraticalSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Preparations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b1e6481-0c73-434e-8756-061e20e16d70"),
                            BalanceId = new Guid("a50bf529-1712-44a8-b12d-d86e336fcf0c"),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DryingTemperature = 100.0,
                            Method = "B",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisualNomialPraticalSize = 0.0
                        });
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8606b885-bde6-4572-8c75-9e714858cf67"),
                            Code = "AAA123",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adelaide Agriculture",
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SampledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SampledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Samples");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45d8f01c-5bca-4267-8d68-5f8f983fedc6"),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barossa Soil ",
                            ProjectId = new Guid("8606b885-bde6-4572-8c75-9e714858cf67"),
                            SampledBy = "Andrew Phan",
                            SampledDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
